package com.bestgroup.downpour.gamecontroller.gameevents;

import java.io.Serializable;

import com.bestgroup.downpour.gamecontroller.GameController;

public class GameEvent implements Serializable {
	
 	/**
	 * 
	 */
	private static final long serialVersionUID = 4136816455584208522L;
	Long userID;
    
	public GameEvent(Long uID) {
		userID = uID;
	}
	
	/*
	 * Default process() creates a NO_RESPONSE GameEvent
	 * Since every event processed by default pushing a new event onto the output queue we
	 * need a GameEvent that is to be ignored. In this case it's NO_RESPONSE or the default
	 * which is generated by the default GameEvenet process() method
	 */

	public GameEvent process(GameController gameController) {
		GameEvent event = new GameEventNoReply(userID);
		return event;
	}			
}
