package com.bestgroup.downpour.gamecontroller.gameevents;

import com.bestgroup.downpour.gamecontroller.GameController;
import com.bestgroup.downpour.gamelogic.Piece;

public class SendSingleP extends GameEvent {
	
 	/**
	 * 
	 */
	private static final long serialVersionUID = 4136816455584208522L;
	Long userID;
    Piece piece;
	
	public SendSingleP(Long uID, Piece p) {
		super(uID);
		piece=p;
	}
	
	/*
	 * Default process() creates a NO_RESPONSE GameEvent
	 * Since every event processed by default pushing a new event onto the output queue we
	 * need a GameEvent that is to be ignored. In this case it's NO_RESPONSE or the default
	 * which is generated by the default GameEvenet process() method
	 */

	public GameEvent process(GameController gameController) {
		GameEvent event = new GameEventNoReply(userID);
		return event;
	}			
}
